Replaced branch name argument to Travis CI install script.

diff --git a/bin/travis/install b/bin/travis/install
--- a/bin/travis/install
+++ b/bin/travis/install
@@ -4,17 +4,31 @@
 #     install - Install Travis CI dependencies
 #
 # SYNOPSIS
-#     install
+#     install <branch>
 #
 # DESCRIPTION
-#     Configures the Travis CI environment and installs ORCA.
+#     Configures the Travis CI environment, installs ORCA, and prepares the SUT.
+#
+# OPTIONS
+#     <branch>
+#         The name of the nearest Git version branch, e.g., 1.x or 8.x-1.x. This
+#         may be the destination branch of a pull request or the nearest
+#         ancestor of a topic branch.
 
 set -e
 
-# Prevent script from being run locally, which can lead to a broken environment.
+# Prevent script from being run locally, which can lead to a broken environment
+# or lost work.
 if [[ -z "$TRAVIS" ]]; then
   echo "Error: This script is meant to run on Travis CI only."
   exit 1
+fi
+
+# Require the branch name argument.
+if [[ -z "$1" ]]; then
+  echo "Missing required branch name argument, e.g.:"
+  echo "$0 8.x-1.x"
+  exit 127
 fi
 
 # Executes a Git command in the Travis CI build directory
@@ -39,3 +53,10 @@ export COMPOSER_EXIT_ON_PATCH_FAILURE=1
 # Install ORCA.
 ORCA_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
 composer --no-dev -d${ORCA_ROOT} install
+
+# Ensure the checked out branch is named after the branch name argument.
+gitc rev-parse --abbrev-ref HEAD
+if [[ $(gitc rev-parse --abbrev-ref HEAD) != "$1" ]]; then
+  gitc branch -f $1
+  gitc checkout $1
+fi
